/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_vulkan_BufferProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_vulkan_BufferProxy
#define _Included_com_g2806_radiante_client_proxy_vulkan_BufferProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_g2806_radiante_client_proxy_vulkan_BufferProxy_WORLD_UBO_SIZE
#define com_g2806_radiante_client_proxy_vulkan_BufferProxy_WORLD_UBO_SIZE 592L
#undef com_g2806_radiante_client_proxy_vulkan_BufferProxy_SKY_UBO_SIZE
#define com_g2806_radiante_client_proxy_vulkan_BufferProxy_SKY_UBO_SIZE 112L
#undef com_g2806_radiante_client_proxy_vulkan_BufferProxy_TEXTURE_MAPPING_ENTRIES
#define com_g2806_radiante_client_proxy_vulkan_BufferProxy_TEXTURE_MAPPING_ENTRIES 4096L
/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_BufferProxy
 * Method:    updateWorldUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_BufferProxy_updateWorldUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_BufferProxy
 * Method:    updateSkyUniform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_BufferProxy_updateSkyUniform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_BufferProxy
 * Method:    updateMapping
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_BufferProxy_updateMapping
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
