/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_pipeline_Pipeline */

#ifndef _Included_com_g2806_radiante_client_pipeline_Pipeline
#define _Included_com_g2806_radiante_client_pipeline_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_pipeline_Pipeline
 * Method:    buildNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_pipeline_Pipeline_buildNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_g2806_radiante_client_pipeline_Pipeline
 * Method:    collectNativeModules
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_pipeline_Pipeline_collectNativeModules
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_pipeline_Pipeline
 * Method:    isNativeModuleAvailable
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_pipeline_Pipeline_isNativeModuleAvailable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_g2806_radiante_client_pipeline_Pipeline
 * Method:    getAttributes
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_g2806_radiante_client_pipeline_Pipeline_getAttributes
  (JNIEnv *, jclass, jstring, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
