/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_world_EntityProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_world_EntityProxy
#define _Included_com_g2806_radiante_client_proxy_world_EntityProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_proxy_world_EntityProxy
 * Method:    queueBuild
 * Signature: (FIZIJJJJJJJJJJJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_world_EntityProxy_queueBuild
  (JNIEnv *, jclass, jfloat, jint, jboolean, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_world_EntityProxy
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_world_EntityProxy_build
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
