/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_world_PlayerProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_world_PlayerProxy
#define _Included_com_g2806_radiante_client_proxy_world_PlayerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_proxy_world_PlayerProxy
 * Method:    setCameraPos
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_world_PlayerProxy_setCameraPos
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
