/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_vulkan_HdrProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_vulkan_HdrProxy
#define _Included_com_g2806_radiante_client_proxy_vulkan_HdrProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_HdrProxy
 * Method:    compose
 * Signature: (JJIIIIJIIFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_proxy_vulkan_HdrProxy_compose
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jlong, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
