/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_option_Options */

#ifndef _Included_com_g2806_radiante_client_option_Options
#define _Included_com_g2806_radiante_client_option_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetMaxFps
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetMaxFps
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetInactivityFpsLimit
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetInactivityFpsLimit
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetVsync
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetVsync
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetChunkBuildingBatchSize
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetChunkBuildingBatchSize
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetChunkBuildingTotalBatches
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetChunkBuildingTotalBatches
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_g2806_radiante_client_option_Options
 * Method:    nativeSetCollectChunkEmission
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_option_Options_nativeSetCollectChunkEmission
  (JNIEnv *, jclass, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
