/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
#define _Included_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_NONE
#define com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_NONE 0L
#undef com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_DLSS
#define com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_DLSS 1L
#undef com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_FSR
#define com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_BACKEND_FSR 2L
/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    backend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_backend
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    setPreference
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_setPreference
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    isAvailable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_isAvailable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    maxGeneratedFramesFor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_maxGeneratedFramesFor
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    evaluateAndBlit
 * Signature: (JJIIIJIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_evaluateAndBlit
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jlong, jint, jint, jboolean);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    presentPending
 * Signature: (J[JJII)I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_presentPending
  (JNIEnv *, jclass, jlong, jlongArray, jlong, jint, jint);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy
 * Method:    waitPresentIdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_FrameGenerationProxy_waitPresentIdle
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
