/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_g2806_radiante_client_proxy_vulkan_RendererProxy */

#ifndef _Included_com_g2806_radiante_client_proxy_vulkan_RendererProxy
#define _Included_com_g2806_radiante_client_proxy_vulkan_RendererProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    initFolderPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_initFolderPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    createInstance
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_createInstance
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    createDevice
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_createDevice
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    isRayTracingCapable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_isRayTracingCapable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    initRenderer
 * Signature: (JJJJIJIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_initRenderer
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jint, jint, jint);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    maxSupportedTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_maxSupportedTextureSize
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    renderFrame
 * Signature: (JIII[J)I
 */
JNIEXPORT jint JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_renderFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlongArray);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    markSubmitted
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_markSubmitted
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    flushTextureUploads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_flushTextureUploads
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    lockQueue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_lockQueue
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    unlockQueue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_unlockQueue
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_close
  (JNIEnv *, jclass);

/*
 * Class:     com_g2806_radiante_client_proxy_vulkan_RendererProxy
 * Method:    shouldRenderWorld
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_g2806_radiante_client_proxy_vulkan_RendererProxy_shouldRenderWorld
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
