#Options
#Wed Sep 23 14:55:15 CDT 2026
biomeFog=true
biomeFogStrength=100
blockLightSampling=true
chunkBuildingBatchSize=12
chunkBuildingThreads=6
chunkBuildingTotalBatches=12
collectChunkEmission=true
debugLogging=false
denoiserMode=1
dlssMode=1
firstPersonShadow=true
frameGeneration=false
generatedFrames=1
inactivityFpsLimit=260
maxFps=260
rayBounces=4
rayTracingEnabled=true
reflex=false
upscalerQuality=1
upscalerType=1
useOpenGl=false
vanillaCelestialOrientation=false
vanillaSunPath=false
vsync=true
